### ISSUE TITLE
Rejection message on Login - Enhancement by Bootstrap

### ISSUE THREAD

**Issue by ButterflyPixels** [kevjava/chronicus-web#3]
If login fails, the alert is the default one. Looks... not great, add Bootstrap later.

**Comment by kevjava** [comment]
Fix instructions are listed in the text for #7.

**Comment by kevjava** [comment]
You also might want to ensure you [empty](http://www.w3schools.com/jquery/jquery_dom_remove.asp) the div before appending the alert to it, just in case the user fails login twice.
